#!/bin/sh
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

program=`basename $0` 
dir=`dirname $0`
cd $dir
logfile="log."$program".txt"
echo `date` "start $*" >> $logfile

export AUTOSSH_POLL=60
export AUTOSSH_FIRST_POLL=30
export AUTOSSH_GATETIME=0
export AUTOSSH_DEBUG=1
autossh -M 0 -qT -N -R "127.0.0.1:43352:172.38.8.89:18888" \
	-o ServerAliveInterval=15 -o ExitOnForwardFailure=yes -o BatchMode=yes -o StrictHostKeyChecking=no \
	guest@host -p 12334 -i sk2 >> $logfile 2>&1
echo `date` "stop $*" >> $logfile

# * * * * * flock -xn /tmp/myreverse.lock -c "reverse" &


